# permissions for end users to edit zookeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zookeeper-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafka-operator
    app.kubernetes.io/part-of: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: zookeeper-editor-role
rules:
- apiGroups:
  - kafka.kafkaop.com
  resources:
  - zookeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.kafkaop.com
  resources:
  - zookeepers/status
  verbs:
  - get
