# permissions for end users to view zookeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zookeeper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafka-operator
    app.kubernetes.io/part-of: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: zookeeper-viewer-role
rules:
- apiGroups:
  - kafka.kafkaop.com
  resources:
  - zookeepers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka.kafkaop.com
  resources:
  - zookeepers/status
  verbs:
  - get
